title: Samuel Morris # your name (or website title) here
logo: "/images/portrait.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Sam Morris a third year student at The University of Manchester studying Computer
  Science.
  <br><br>
  Currently on the search for an Industrial placement from August 2023.
  <br><br>
  <a href="https://www.linkedin.com/in/sam-morris-b02068224/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-1FMHL7LBL1 # your Google Analytics tracking ID here
